### ISSUE TITLE
A small question

### ISSUE THREAD

**Issue by pple7000** [Ch0pin/AVIator#2]
How to run this tool?
Just like commands,dependents or something like this

**Comment by Ch0pin** [comment]
In order to run the tool you either have to clone the repo and use a compiler in order to compile the project (e.g. in visual studio) or you can download the executable file from the already compiled project. The only dependency is the .net framework. By running the executable (see screenshot https://ibb.co/X24mnzW) , you just have to follow the instructions at the left side of the main form. I will compile the latest version and upload it by the end of the day.

**Comment by pple7000** [comment]
Got it! 
And that is say.If I want to run it on Kali Linux,I have to use wine.
Correct?

**Comment by Ch0pin** [comment]
I guess you can use the 'mono' framework. 
But, let me do the test and get back on this

**Comment by pple7000** [comment]
OK,thanks.

**Comment by Ch0pin** [comment]
Confirmed:

#apt update 
#apt install mono-devel

and finally run:

#mono aviator.exe

**Comment by pple7000** [comment]
I realize!!!Thanks
